notifications:
  email: false

dist: xenial

sudo: required

language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'

addons:
  apt:
    packages:
      - xvfb
      - xsel

deploy:
  true:
    branch: master
  distributions: sdist bdist_wheel
  user: mandeepb
  provider: pypi
  edge:
    branch: v1.8.45
  password:
    secure: u20FWnJqHoDXWBQ6xJ0+a8ymfIFp1l51m5sWxDaN6JolXmPvL7Y0HGHDbcW4d5+ltGCiihj6Lbxcquzz16GYAHnoQeCrG7p/UzSbR3OCgzn/SxwmrphePzhuWULPl7rb/vz2r7sjAmfES/p8kO/34NZOJuubrzUy5q5p9RjiimBjuH3R1KwaI6/tigIegSaM1HMMxyWDejqCGsujbpSzbSyjuhQ2Joh275R8JwDHdz4cWwhJrVtRochhSGgLacnPTOBKZN4RlbpiW/+/aM4PzffxXpZISMVGqu6WLGwxfDGJxyyX4VzTrqMNFNetjeGO1J/xnvKDj0OAKh3NNNoluN6X60xxwr+RZVEg5+Jj4+bkAPAk5fc3nDt8VV3s3G5visQ0GmXDhvX38gbEdAwVz+5wVny7egZX4IsDlSkwZ5si2TnFEQ3HkPJAUPXSHFBrRHIcZJYfTyI+Gm/yQp8I0jgz1OrGUqN9sMxu7j92rMDaz6u0Yt0nWkG9OMVdGOF5fyTW5JM2gv/gKutEFHDEBzZcbkB9RJQQRNjK0MdThtXVoZ5RakrEGKH1o4728YG4Rnj3KlbXeigUFJ+0OGmQFP4nA2acJyC64g5V+LX5RJl04Mqky5fKF7nNbSJeRZA1teVrhhe+ifMg+/02KRjmHZ5qx5QS3cAJih9UPP7zwbA=

install:
  - pip install cryptography pytest pytest-cov pytest-xvfb six mock coveralls --upgrade
  - python setup.py install

script:
  - pytest -v --cov=.

after_success:
  - coveralls
